var mongoose=require("mongoose");
var SchemaTransferencia=new mongoose.Schema({
	motorista:String,
	matricula:String,
	pneus:String,
	parabrisas:String,
	porcas_parafusos:String,
	luzes:String,
	oleo_motor:String,
	liquido_refrigerante:String,
	nome_condutor:String,
	nome_supervisor:String,
	nome_receptor:String,
	data_transferencia:String,
	marca_modelo:String,
	quilometragem:Number,
	razao:String,
	intervenientes:[String],
	status:String,
	total:Number,
	estagio:[Number],
	datta:String,
	vidros:String,
	nivel:String,
	kilometragem:String,
	carrocaria:String,
	razaoCarrocari:[String],
	razaoCamera:[String],
	razaoPneus:[String],
	razaoPressao:[String],
	razaoPorcas:[String],
	razaoVidros:[String],
	razaoLuzes:[String],
	razaoNivel:[String],
	razaoTravoes:[String],
	porcas:String,
	sinalizacao:String,
	pressao:String,
	oleo:String,
	refrigeracao:String,
	travoes:String,
	observacao:String,
	camera:String,
	handsfree:String,
	regiao:String,
	data_real:{type:Date, 'default':Date.now},
	num_notificacao:{type:Number, 'default':0},
	date_diference:{type:Number, 'default':6000},
	despachado_por:String,
	data_despacho:String
})
SchemaTransferencia.statics.gravarDados=function(transferencia, callback){
	this.create(transferencia, callback);
}

module.exports= mongoose.model("Transferencias", SchemaTransferencia,"Transferencias");